name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Container
        run: |-
          docker build -t ghcr.io/jtmiclat/tippecanoe-docker:latest .
          docker push ghcr.io/jtmiclat/tippecanoe-docker latest
